### PR TITLE
wasm as platform dependency

### LINKED ISSUE #134: `wasm` feature flag instead of platform-dependent dependencies
Hello !

Currently, this crate fails to compile in wasm, unless the `wasm` feature flag is provided.

This comes from the fact that wasm-specific dependencies are specified under a feature flag instead of being specified as [platform-specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) : 

https://github.com/oxfordcontrol/Clarabel.rs/blob/7036899fda1c3c95bbee894bd9babce4f2e66c40/Cargo.toml#L58

Using platform-specific dependencies with 

```toml
[target.'cfg(target_family = "wasm")'.dependencies]
some_wasm_specific_dep = "0.0.0"
```

would allow the code to compile for wasm without having to specify a feature flag.

This is especially useful to users for whom clarabel is a sub-dependency.

See https://github.com/rust-or/good_lp/pull/63

### PR DESCRIPTION
**Pull request by goulart-paul**
Attempts to fix #134.

### CODE REVIEW

**Review by lovasoa — APPROVED** [review]
Great !

File: src/timers/timers.rs [hunk 1]
```diff
@@ -2,14 +2,13 @@ use std::collections::HashMap;
...
 
 cfg_if::cfg_if! {
-    if #[cfg(feature="wasm")] {
+    if #[cfg(target_family = "wasm")] {
         use web_time::{Duration, Instant};
     }
     else {
         use std::time::{Duration, Instant};
     }
 }
```
Comment (lovasoa) [inline src/timers/timers.rs:11]: @goulart-paul Is there a reason to use cfg-if here ? (Instead of just adding the `#cfg` attribute directly ? 

https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg-attribute

Comment (goulart-paul) [reply src/timers/timers.rs:11]: I think either way works.    Maybe the current way is slightly preferable since it presents the cases as mutually exclusive options?    

We already depend on cfg-if anyway since it is used when configuring basic types with/without BLAS support, and there cfg-if is quite useful since the `else` blocks can have (marginally) more substance.
